version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
